### PR TITLE
Added Curve_Division

### PR DESCRIPTION
**Pull request by lin-ycv**
-corrected formating
-Contour : Complete
-Divide Curve : Complete

### CODE REVIEW

**Comment by garciadelcastillo** [comment]
Looking pretty good @v-xup6 :)

**Comment by lin-ycv** [comment]
@garciadelcastillo all finished except contour and contour(ex) outputs to wrong path if input is more than one item.
code has been cleaned up to better match the code style standard for GH#

**Comment by garciadelcastillo** [comment]
Very nice work @v-xup6 ! Code looks great to me, let's merge! 

A couple minor things to fix:
- When I open `Math_Operators.ghx` the file is zoomed somewhere far out. Try to save files with zoom centered around the file header.
- Rename `Curve.Division.ghx` to `Curve_Division.ghx`. I agree the first is nicer to read, but let's keep it this way for consistency with the rest of the project. We can change all files before release if we feel like.

**Comment by garciadelcastillo** [comment]
Thanks! 🥳 👍

**Pull request merged**
