### PR TITLE
Sets tree batch1

### PR DESCRIPTION
**Pull request by sonomirco**
- Developed the first 8 components of the tree set.
- Updated the ReadMe file.

### CODE REVIEW

**Comment by garciadelcastillo** [comment]
Awesome, thanks a lot @sonomirco, this is really good quality work! The code is very well documented and thorough, great job! 👍 💯 

A couple minor comments:
- For Simplify Tree, perhaps the input data could have a set of initial zeroes `{0;0;0} {0;1;0} {0;2;0}...`, so that it is easier to see the difference when Front is active (everything is cleaned) or not (only the initial zeroes are).
- Remember when finishing the file to deactivate the preview of all components; we do not want users opening the file and having a ton of geometry on the viewport. This is not so important for this category, but more important for others.  
- Since the `Sets.Tree` category has components arranged in two columns, you may want to arrange them that way as well on the file as well:
image

Keep it up! 💪

**Comment by garciadelcastillo** [comment]
What would you like to do? Would you like to incorporate feedback and merge, or keep working on this PR for the rest of the components?

**Comment by sonomirco** [comment]
I'll prefer to incorporate the feedback and merge.
I'll work for batches so it would be easier to review and incorporate feedback.
image

**Comment by sonomirco** [comment]
incorporated the feedback, you can marge when you want, and I'll start with the second batch.
Mirco

**Comment by garciadelcastillo** [comment]
Alright, merged!! Thanks a lot @sonomirco ! 🥳 🥳 🥳 🥳 

Please make sure to update your local fork before starting a new PR. 

Cheers!

**Pull request merged**
