### PR TITLE
Updated Curve.Analysis

### PR DESCRIPTION
**Pull request by lin-ycv**
Still needs work:
Planar
Curvature Graph
Curve Side
Derivatives
Torsion
Point In Curve
Point In Curves

### CODE REVIEW

**Comment by garciadelcastillo** [comment]
Amazing work @v-xup6 , thanks!

A general comment: can you take a look at the fnt size of your panels? Yours are much smaller than what we are using for the rest of the components. This is probably a problem due to retina screens or working on a system with a different native char set:
image

Maybe copy-pasting previous panels and resizing them would solve this?

For components:
`IsPlanar`: 
-  When the curve is not planar, my guess is that the original component is sampling a bunch of points on the curve (for example 100 points equally distributed across the curve's internal domain) and fitting the Plane to these. Want to give this a try?
- The deviation in this case can be found as an additional `out` in the `FitPlaneToPoints` method: `Plane.FitPlaneToPoints(nCrvPt, out pln, out deviation);`

`CrvGraph`: What's the state of this one?
`Curve Nearest Object `: ✔️ 
`Curve Side`: I think it's ok to not implement the input plane ✔️ 
`Extremes`: nicely done! ✔️ 
`Curvature`: ✔️  Can we properly align the output panels?
image
`Derivatives`: The tangent is not working because it is unitized, not taking into consideration the actual speed. Try this:
```
    Vector3d[] deriv = C.DerivativeAt(t, 1);

    P = deriv[0];
    V = deriv[1];
```
Interestingly, the component has dynamic outputs, allowing for 2nd, third and so on derivatives... I have an open question about using volatile data in C# components: https://discourse.mcneel.com/t/output-addvolatiledata-in-c-script-component-overridden-with-null-element/113520, but in the meantime, perhaps you just want to add more outputs to show the functionality?
`Evaluate Curve`, `Perp Frame`: ✔️ 
`Torsion`: want to try experimenting with the cross product of the first and second derivatives? 
`Evaluate Length, Length Domain, Segment Lengths`: ✔️ 
`Point In Curve and Curves`: I think the problem here is that you are assuming you _always_ project the points to the WorldXY plane. Have you tried _trying to get the curve plane_ first with `C.TryGetPlane(out pln, tolerance)`, and fall back to XY if failed? For the tolerance, you can use some dimension of the curve's BoundingBox for example or leave it blank. 

Let's take `Primitives` out of this PR and start one on its own for review.

Thanks, keep it up! 💪

**Comment by lin-ycv** [comment]
@garciadelcastillo 
Will adjust the font sizing, though for panel sizing I can only guess, since font sizing will be off on my screen

For `IsPlanar`,  using curve division points to find the plane was actually my first attempt, but the results were not correct, 
Below is the result using DivideByCount
image
I've tried using multiple different methods of getting different sets of points from the curve (discontinuity, divide length, count, eq distance...), none of them worked.

`CrvGraph` is a tricky one, I assume the graph result is correct, the problem is that the vanilla input for density and scale is not self explanatory. For scale, it has to start from 20, and the scale factor seems to be exponential. For density, it also seems like there's some kind of equation that it's suppose to go into. So it's a huge question mark regarding the technical how of how these two input affects the output.

Not sure I understand what `Derivatives` is, need to refresh my math, but I've corrected the code accordingly and implemented the dynamic output. Not sure how beginner friendly it is, but I've tried to comment as much as possible.

`Torsion`: I need to review my math first, I don't really remember what cross product of derivatives represent.

`Point In Curve and Curves' : I'm defaulting to XY plane mainly because I haven't figured out how to determine the curve plane (same issue as `IsPlanar`)

I'm not very familiar with Github, if I make a PR and update files, they automatically get added to the PR, how do I remove them from the PR and start its own?

**Comment by garciadelcastillo** [comment]
If you are not getting it, just leave IsPlanar as incomplete with a warning. For CrvGraph, feel free to fix it to do something similar (although maybe not accurate), or clear it out completely. 

For dynamic outputs, I have a conversation going on with @bava-kumaravel on whether it is convenient for us to do it, or it just adds too much overhead and distracts from the main educational point of the project. We also asked this question on how to implement it better: https://discourse.mcneel.com/t/output-addvolatiledata-in-c-script-component-overridden-with-null-element/113520/4. If you think it makes the code too unclear, just fix 3 outputs and implement for that. If it is not too much overhead, then implement dynamic outputs and comment on the code appropriately. 

Torsion: give it a try with the cross product, lmk if you have questions. 

Point in Curve: try using `curve.TryGetPlane()` to get a plane from the curve and project on that, and if this fails, then you back to XY. 

Leave this PR as it is and let's merge it whenever `Primitives` is done. For the future, the best way is to start a branch on your repo, do all the changes for a Category there, and do a PR from that branch into `master` here. Once the PR goes through, you can delete your branch and update your fork from this repo's `master`. Lmk if you have more questions on this. 

Lmk when you think you are ready for another review :)

Thanks!

**Comment by bava-kumaravel** [comment]
Hello @garciadelcastillo and @v-xup6 ,

I have tried out the dynamic output for the components - Sift, Longest List and Shortest List in the Sets-List Tab. I preferred to try dynamic outputs over the default 2 input-outputs for these components because without dynamic inputs and outputs, I felt the script was just too trivial for just 2 inputs, especially for shortest list and longest list. To do this, I have declared a datatree to hold the outputs of all the output parameters in separate branches. I have declared this datatree as a persistent variable, outside the RunScript() function. And, at the beginning of the RunScript() function, I just clear out its values. And in the AfterRunScript() function, I use a for loop to assign the values from the datatree to the corresponding output parameters. I again clear out the output parameters before I assign values to them, so that the null values assigned to them from the RunScript() function get deleted. These are the comments I have left for the readers. Like I had discussed with @garciadelcastillo over mail, I believe this will be good learning exercise for intermediate level users.

image

image

**Comment by garciadelcastillo** [comment]
Hey @v-xup6 , good job! I am very happy we finally got `Primitives` done! Good job! 🥳🥳🥳

A couple comments:
- I worry that in `Tangent Lines`, when "slightly left and right to get the two tangents" using `+-1`, this may only work for large circles but fail for ones with a small domain. Would this work if we did a small number than `1`?
- Not sure what's happening with `InEllipse`, but result is close enough, I would keep as is. 
- Same thing with `BiArc`. 

To do before merge:
- [ ] Check precision for `Tangent Lines` (see above).
- [ ]  For `Tangent Lines In` feel free to remove the old not working code but leave the previous authors who tried as a sign of recognition :)
- [ ] Make sure to disable preview of the two input points in `BiArc`. 
- [ ] Save file with "zoom extent"

**Comment by garciadelcastillo** [comment]
As for our conversation about `Torsion`, if you look at the Wolfram alpha definition:
https://mathworld.wolfram.com/Torsion.html

Turns out torsion is the [Scalar Triple Product](https://mathworld.wolfram.com/ScalarTripleProduct.html) of the first three derivatives (Tangent, Normal and [Abberrancy](https://www.jstor.org/stable/2690245?seq=1)/Jerk), divided by the cross product of the first two derivatives (Tangent X Normal = Binormal) squared. This can then be summarized as:
```
    // https://mathworld.wolfram.com/Torsion.html
    //      |c' c'' c'''|   c''' · (T x N)   c''' · B
    //  t = ------------- = -------------- = --------
    //      |c' x c''|^2       B · B          B · B
    //
``` 

So, how about this?
```
    Vector3d[] deriv = C.DerivativeAt(t, 3);
    Vector3d binormal = Vector3d.CrossProduct(deriv[1], deriv[2]);
    double c3 = deriv[3] * binormal;
    double b2 = binormal * binormal;
    if (binormal.Length == 0)
    {
      P = deriv[0];
      T = 0.0;
      return;
    }

    P = deriv[0];
    T = c3 / b2;
```

**Comment by lin-ycv** [comment]
@garciadelcastillo it's ready for a merge now
- [x] Precision for Tangent Lines: used 50*document tolerance, which is 0.05, won't work if too little.
- [x] Tangent Lines: Old code removed, recognition still there
- [x] Two input points in BiArc preview disabled
- [x] Save file with "zoom extent"
- [x] Torsion now working

@bava-kumaravel good catch on the clearing persistant data, I totally missed that in my implementation for derivative 

Will move on to Curve.Util

**Comment by garciadelcastillo** [comment]
Awesome @v-xup6 , merged! 🥳 🥳 🥳 🥳 

Make sure to update your local branch with these changes before starting a new PR! 

Thanks! :)

**Pull request merged**
