### PR TITLE
Sets text

### PR DESCRIPTION
**Pull request by sonomirco**

### CODE REVIEW

**Comment by garciadelcastillo** [comment]
Thanks Mirco for your first contribution. This looks great, and we appreciate your lenghty and detailed comments, as well as some areas where you actually provide different variants of how to do text manipulations, nice!!! :)

I only have minor stylistic requests before approval, just for the sake of consistency with the rest of the project:
- We are nicknaming components with the _abbreviated_ nickname of the original one, with a whitespace in the middle. So for instance, instead of `GH#TextFragment`, it would be `GH# Fragment`. You can check thses nicknames if you hover over the original component, it would be the name in parenthesis.
- Panel colors are HSVA (0, 0, 100, 255). Yours look too grayish. 

The rest is really really nice and neat, great work @sonomirco ! 💪 Happy to approve whenever the above is resolved. 

In general, for the future, we discourage the use of `while` loops wherever a `for` loop could do the work. Not a big deal, just something to keep in mind. 

Also, for `Text Distance`, in the `LevenshteinDistance` function, perhaps you could rewrite the function a little to make it more readable and understandable? I am looking at the two for loops that are populated with i j values inline (a little convoluted) as well as the use of `var` (discouraged).

**Comment by garciadelcastillo** [comment]
Oh, also, the `Sets_Text` scribble at the beginning of the file should have an underscore (sorry, my OCD kicking in... :)

**Comment by sonomirco** [comment]
> Thanks Mirco for your first contribution. This looks great, and we appreciate your lenghty and detailed comments, as well as some areas where you actually provide different variants of how to do text manipulations, nice!!! :)
> 
> I only have minor stylistic requests before approval, just for the sake of consistency with the rest of the project:
> 
> * We are nicknaming components with the _abbreviated_ nickname of the original one, with a whitespace in the middle. So for instance, instead of `GH#TextFragment`, it would be `GH# Fragment`. You can check thses nicknames if you hover over the original component, it would be the name in parenthesis.
> * Panel colors are HSVA (0, 0, 100, 255). Yours look too grayish.
> 
> The rest is really really nice and neat, great work @sonomirco ! 💪 Happy to approve whenever the above is resolved.
> 
> In general, for the future, we discourage the use of `while` loops wherever a `for` loop could do the work. Not a big deal, just something to keep in mind.
> 
> Also, for `Text Distance`, in the `LevenshteinDistance` function, perhaps you could rewrite the function a little to make it more readable and understandable? I am looking at the two for loops that are populated with i j values inline (a little convoluted) as well as the use of `var` (discouraged).

Hi Jose,
Clear and neat!
Yeah, I thought about the LevenshteinDistance to make it more readable.
Not a problem at all, I'll do it all the changes, and thanks for the info.

**Comment by sonomirco** [comment]
@garciadelcastillo file updated.

**Comment by garciadelcastillo** [comment]
Yuhuuuu, nice! 🎉 🎉 
Merging! ⏫ 
Also @sonomirco , do not forget to update your current fork, to reflect changes that are happening in parallel! :)

**Pull request merged**
