### PR TITLE
Adding Sets_List

### PR DESCRIPTION
**Pull request by bava-kumaravel**
All components are complete, with a minor doubt on ListIndex component. Sift, LongestList, ShortestList implemented with dynamic outputs (Alternate implementations with static outputs, yet to be made)

### CODE REVIEW

**Comment by bava-kumaravel** [comment]
Also, following our conversation on Insert component Jose, I rewrote the component to find that it now works very much in line with the original component. So I have marked it complete. As for ListIndex, I tried following the Geometry Input approach you mentioned. So I have created a list of points stored in a Geometry object, then I have referenced one item from it using the ListItem component and then I pass it to the ListIndex components. If I store the referenced item, in a separate Geometry Object and internalize it I still get the -1 value error in the vanilla GH component. So should I leave it this way, with the ListItem component used?

image

image

Then lastly, I haven't yet implemented the static versions of the Static, Longest List and Shortest List. Like you said, I felt this would indeed be a good learning exercise. But do let me know if think it would be better to have the static versions too, in which case I can add them to the file. Your call :)

**Comment by bava-kumaravel** [comment]
In the Longest List and Shortest List components - I have an issue with the 'Interpolate' options. I referred to this forum entry https://www.grasshopper3d.com/forum/topics/controlling-longest-list-behaviour to understand its behavior. So divided the list into intervals to match the length of the desired list's length and then interpolated its values based on their rounded off values. But the results aren't the same in most cases with the vanilla GH component. I tried all the different rounding off strategies - Round, Floor and Ceil, still I couldn't get the exact same results. So I have left a warning message for that one option alone.

image

image

**Comment by garciadelcastillo** [comment]
Hi @bava-kumaravel, amazing work as usual! You really killed it on this one, I am very impressed. The contribution is super comprehensive and well explained. I mean, seriously, have you seen the `Cross Reference` code...? Really bad ass! 👍 💯 😮 

For item index, yes, the situation you describe where two points have the same coordinates yet are "different" is because, since they were created differently, they have two different memory addresses and therefore count as different objects when compared. This is normal, and your workaround to actually fetch one from the list and use it for comparison is really good. I would mark this one as done 😄 

As for the 'interpolate' issue, I have no idea what might be going on there, so don't bother and the warning for that case is a good idea. I would also mark that one as done. 

I say you change the warning on `Item Index` to "this component only works with geometry objects, not primitives", and we merge! 🥳

**Comment by bava-kumaravel** [comment]
Thank you for your kind words Jose @garciadelcastillo :) I also discovered something today that the List Index component works with Primitives too, just as long as its referenced through a List Item component 😄 So I just took off the warning message all together and flagged it complete! Yay! I also replaced the geometry input with the primitives list input that I used for the other components to maintain homogeneity.

image

**Comment by garciadelcastillo** [comment]
Nice! That might be because GH wraps all data into `IGH_Goo` objects, so references are maintained? In any case, happy to hear that! 

I wonder if you would mind changing the input list for `Item Index` before merging? I find it confusing that asking for fourth element retrieves number four... lol. Can we make the inputs either a randomized list of numbers, or back to some geometry entities? 

Thanks!

**Comment by bava-kumaravel** [comment]
Haha I see what you mean. I have reverted to the Geometric inputs :)

**Comment by garciadelcastillo** [comment]
Merging, yaaaay! 🥳 🥳 🥳 

Thanks a lot @bava-kumaravel , good job! 💪 

Please make sure to update your local fork before starting a new PR.

Cheers!

**Pull request merged**
