### PR TITLE
Adding Sets_Sequence

### PR DESCRIPTION
**Pull request by bava-kumaravel**
All components are complete, except for the Jitter component which has minor difference in outputs from the original

### CODE REVIEW

**Comment by bava-kumaravel** [comment]
The jitter component randomizes a list based on the strength of the jitter which varies between 0.0 and 0.1. I referred to this forum post to write this component - https://discourse.mcneel.com/t/explanation-of-jitter-component/52939
From the post, I have declared a value r = strength x length of list
And then using this value r, he creates domains for individual elements in the list within which a random double can be computed - He does this as (i-r, i+r). But when I do this, the domain for randomization is almost 50% negative for lower indices creating a bias that doesn't let them get shuffled as much as the higher indices in the list can.
image

So I thought, if the value of r could be multiplied with a factor, the bias can be lifted. So as a random value I tried multiplying it with a factor of 100, which gives me the right output for almost all seeds, but only for jitter strength of 1.0. I guess the factor is too high that it overshadows the jitter strength. I'm not able to fix on the right factor here, which would give the right outputs for all values of strength. 
image
image

If there is any alternate approach, or if the factor can be found with an expression from the strength, kindly let me know :)

**Comment by sonomirco** [comment]
Did you try to constrain the min to zero and the max to the L.Count?
Because the jitter is limited between 0.0 to 1.0 so I was thinking maybe limiting the min and max inside the dimension of the list is enough.
So what I am saying is:
double min = Math.Max(index - r, 0.0)
double max = Math.Min(index + r, L.Count)

**Comment by bava-kumaravel** [comment]
Thank you @sonomirco for your comment. I have written r = J * L.Count (Leaving out the 100 factor) and constrained min and max within the limits of the list index, as per your suggestion. The component works way better now. 

image

image

There are still a few minor differences though. But I guess it is natural with a component that involves random numbers and double. @garciadelcastillo, kindly let us know your comments on this :) 

image

**Comment by garciadelcastillo** [comment]
Hi @bava-kumaravel , and sorry for the wait time! 

Nice job, you killed the Sequence components! 💪 

Some minor comments:
- The `Sequence` component is 🔝 !
- `Random Reduce` looks good to me, same results as original, except if R is 0, which leaves the list untouched. Can you please fix this cornercase?
- I am very ok with how the `Jitter` component works now, and passing it as-is. 

Please fix the `Random Reduce`, and let's merge!

**Comment by bava-kumaravel** [comment]
Hi @garciadelcastillo ,

Thank you for your comments. I have fixed the R=0 case in the Random Reduce component. However I have left the warning message on the Jitter component as it was. Should I remove it and mark it done, or is this okay? Kindly let me know.

**Comment by garciadelcastillo** [comment]
Sounds good, let's leave the warning on `jitter` for future development.

Merging, yaaaay! 🥳

**Pull request merged**
