### PR TITLE
Added the second batch for the tree set

### PR DESCRIPTION
**Pull request by sonomirco**

### CODE REVIEW

**Comment by garciadelcastillo** [comment]
Hi @sonomirco , 

And sorry for the late review, crazy start of the year! 

Can I say... this PR is 💪 💪 💪 💪 ! AMAZING JOB!

My only main comment is: there are some components where the input is a `DataTree` (like Flip, or Match) but instead of using this structure directly, you fetch the volatile data instead. Why do so? Is this what's causing that these components can get intpus/outputs inserted? 

image

In general, I believe that if the original component doesn't accept variable IOs, we shouldn't do it either. Let me know what you think about this, and whether if we should let it stay or can easily fix this. 

Other comments:
- Your `Path Mapper` is simply 💯 💯 💯 💯 💯 !  
- There is a typo in the `Marge` component 🤣 
- We typically do not remove the `out` output of the C# components. However, I believe you have done so to avoid problems with variable IOs, correct?  

Let me know what you think about the above, and whether to fix the variable IOs or let it be and merge. 

Thanks!

**Comment by garciadelcastillo** [comment]
Oh no wait, I got super confused: C# script components always have variable inputs!!! OMG, it's really been a crazy start of the year 😅 

Nevermind, we are good on that front. Please fix the typo, and let's merge!

**Comment by sonomirco** [comment]
Hey @garciadelcastillo.
Not a problem 👍 
Typo fixed, and merge, and I can move to the next batch :)

**Comment by garciadelcastillo** [comment]
Merged, yaaay! 🎉🎉🎉

**Pull request merged**
